area1_x: 1.423
area1_y: -2.683
area1_orientation: -1.374

area2_x: 2.644
area2_y: -3.772
area2_orientation: 0.270

area3_x: 2.325
area3_y: -4.105
area3_orientation: -1.342

area4_x: 1.388
area4_y: -4.318
area4_orientation: -1.289

area5_x: 0.623
area5_y: -4.167
area5_orientation: -2.969

casa_x: 1.223
casa_y: -2.027
casa_orientation: -1.418

deposito_x: 0.419
deposito_y: -2.828
deposito_orientation: 1.866

pedido_x: 2.290
pedido_y: -2.381
pedido_orientation: 1.770
